### ISSUE TITLE
Framework type

### ISSUE THREAD

**Issue by ajakubo1** [EnviroMonitor/EnviroMonitorFrontend#1]
@zen @devnook @grillazz 

Guys, any preferences on the frontend framework?

I won't lie, I really want to do it in React/Redux, but do let me know if you have any objections. I'll gladly help out with understanding the code (though I myself work in React for about 2-3 months, so I'm not a master at it :D).

**Comment by grillazz** [comment]
@ajakubo1 I have no preferences.

**Comment by lechup** [comment]
:+1: for React/Redux, but I'm not also React guru...
