### ISSUE TITLE
Move  files from `./EnviroMonitorFrontend/` to root project directory

### ISSUE THREAD

**Issue by lechup** [EnviroMonitor/EnviroMonitorFrontend#10]
@grillazz @ajakubo1 I think we should remove duplicated folder that we have in our project dir.

``lechup@lechup-ubuntu:~/github/EnviroMonitorFrontend/EnviroMonitorFrontend$``

Do we actually need it?

**Comment by ajakubo1** [comment]
Nope, when it comes to me, you can move it. I just duplicated the file structure from ``EnviroMonitorWeb``. Actually, I wanted to do do it myself before I made the first pull request, but it slipped my mind ;).

**Comment by lechup** [comment]
@ajakubo1 can You check my PR closing this issue?
