### ISSUE TITLE
Add an option to have continious coverage reports

### ISSUE THREAD

**Issue by ajakubo1** [EnviroMonitor/EnviroMonitorFrontend#9]
Suggested by @lechup - it would be a command which would look like ``npm run coverage:watch``.

**Comment by lechup** [comment]
Hm... Now I'm thinking - should we even bother? It should be CI that calulcates it? Maybe there is plugin for travis / github that enable nyc integration or we can use one of:
* https://docs.travis-ci.com/user/coveralls/
* https://docs.travis-ci.com/user/code-climate/

Any thoughts?

**Comment by ajakubo1** [comment]
Yeah, I've did some checks and I don't think it's possible with nyc (just as you said :))

But I did find this in nyc documentation:

https://github.com/istanbuljs/nyc#integrating-with-coveralls

It would be neat to have the button for coverage reporting, and to set some sensible limits on it :).

**Comment by lechup** [comment]
Ok, merged #14  closing this one...
